// this is a normal comment (normal)
//?   Is this a comment? (duvida)
//!   This shouldn't be a comment (alerta)
//*   This is a highligthed comment (destaque)
//TODO: You should comeback and reDO IT in the future (future updates)
//// this is a deleted comment (deleted code)